// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ordersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _placeorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func __7border_id_7dMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _markorderpaidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listorderMw() []app.HandlerFunc {
	// your code...
	return nil
}
