// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	order "2501YTC/app/gateway/biz/router/order"
	product "2501YTC/app/gateway/biz/router/product"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	order.Register(r)

	product.Register(r)
}
