// Code generated by hertz generator. DO NOT EDIT.

package router

import (

	auth "2501YTC/app/gateway/biz/router/auth"
	order "2501YTC/app/gateway/biz/router/order"
	product "2501YTC/app/gateway/biz/router/product"
	user "2501YTC/app/gateway/biz/router/user"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	auth.Register(r)

	user.Register(r)

	order.Register(r)

	product.Register(r)
}
