// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	ai "2501YTC/app/gateway/biz/router/ai"
	cart "2501YTC/app/gateway/biz/router/cart"
	checkout "2501YTC/app/gateway/biz/router/checkout"
	order "2501YTC/app/gateway/biz/router/order"
	product "2501YTC/app/gateway/biz/router/product"
	token "2501YTC/app/gateway/biz/router/token"
	user "2501YTC/app/gateway/biz/router/user"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	token.Register(r)

	ai.Register(r)

	checkout.Register(r)

	cart.Register(r)

	user.Register(r)

	order.Register(r)

	product.Register(r)
}
