// Code generated by Kitex v0.9.1. DO NOT EDIT.

package authservice

import (
	ai "2501YTC/rpc_gen/kitex_gen/ai"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"SearchforOrder": kitex.NewMethodInfo(
		searchforOrderHandler,
		newSearchforOrderArgs,
		newSearchforOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	authServiceServiceInfo                = NewServiceInfo()
	authServiceServiceInfoForClient       = NewServiceInfoForClient()
	authServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return authServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return authServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AuthService"
	handlerType := (*ai.AuthService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ai",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func searchforOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(ai.SearchforOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ai.AuthService).SearchforOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *SearchforOrderArgs:
		success, err := handler.(ai.AuthService).SearchforOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*SearchforOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newSearchforOrderArgs() interface{} {
	return &SearchforOrderArgs{}
}

func newSearchforOrderResult() interface{} {
	return &SearchforOrderResult{}
}

type SearchforOrderArgs struct {
	Req *ai.SearchforOrderReq
}

func (p *SearchforOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(ai.SearchforOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *SearchforOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *SearchforOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *SearchforOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *SearchforOrderArgs) Unmarshal(in []byte) error {
	msg := new(ai.SearchforOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var SearchforOrderArgs_Req_DEFAULT *ai.SearchforOrderReq

func (p *SearchforOrderArgs) GetReq() *ai.SearchforOrderReq {
	if !p.IsSetReq() {
		return SearchforOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *SearchforOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SearchforOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type SearchforOrderResult struct {
	Success *ai.SearchforOrderResp
}

var SearchforOrderResult_Success_DEFAULT *ai.SearchforOrderResp

func (p *SearchforOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(ai.SearchforOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *SearchforOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *SearchforOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *SearchforOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *SearchforOrderResult) Unmarshal(in []byte) error {
	msg := new(ai.SearchforOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *SearchforOrderResult) GetSuccess() *ai.SearchforOrderResp {
	if !p.IsSetSuccess() {
		return SearchforOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *SearchforOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.SearchforOrderResp)
}

func (p *SearchforOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SearchforOrderResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) SearchforOrder(ctx context.Context, Req *ai.SearchforOrderReq) (r *ai.SearchforOrderResp, err error) {
	var _args SearchforOrderArgs
	_args.Req = Req
	var _result SearchforOrderResult
	if err = p.c.Call(ctx, "SearchforOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
