// Code generated by Kitex v0.9.1. DO NOT EDIT.

package orderservice

import (
	ai "2501YTC/rpc_gen/kitex_gen/ai"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"QueryOrder": kitex.NewMethodInfo(
		queryOrderHandler,
		newQueryOrderArgs,
		newQueryOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"AutoOrder": kitex.NewMethodInfo(
		autoOrderHandler,
		newAutoOrderArgs,
		newAutoOrderResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	orderServiceServiceInfo                = NewServiceInfo()
	orderServiceServiceInfoForClient       = NewServiceInfoForClient()
	orderServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return orderServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return orderServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "OrderService"
	handlerType := (*ai.OrderService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ai",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func queryOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(ai.OrderQueryReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ai.OrderService).QueryOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *QueryOrderArgs:
		success, err := handler.(ai.OrderService).QueryOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newQueryOrderArgs() interface{} {
	return &QueryOrderArgs{}
}

func newQueryOrderResult() interface{} {
	return &QueryOrderResult{}
}

type QueryOrderArgs struct {
	Req *ai.OrderQueryReq
}

func (p *QueryOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(ai.OrderQueryReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *QueryOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *QueryOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *QueryOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *QueryOrderArgs) Unmarshal(in []byte) error {
	msg := new(ai.OrderQueryReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryOrderArgs_Req_DEFAULT *ai.OrderQueryReq

func (p *QueryOrderArgs) GetReq() *ai.OrderQueryReq {
	if !p.IsSetReq() {
		return QueryOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QueryOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type QueryOrderResult struct {
	Success *ai.OrderQueryResp
}

var QueryOrderResult_Success_DEFAULT *ai.OrderQueryResp

func (p *QueryOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(ai.OrderQueryResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *QueryOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *QueryOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *QueryOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *QueryOrderResult) Unmarshal(in []byte) error {
	msg := new(ai.OrderQueryResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryOrderResult) GetSuccess() *ai.OrderQueryResp {
	if !p.IsSetSuccess() {
		return QueryOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.OrderQueryResp)
}

func (p *QueryOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QueryOrderResult) GetResult() interface{} {
	return p.Success
}

func autoOrderHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(ai.AutoOrderReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ai.OrderService).AutoOrder(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *AutoOrderArgs:
		success, err := handler.(ai.OrderService).AutoOrder(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*AutoOrderResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newAutoOrderArgs() interface{} {
	return &AutoOrderArgs{}
}

func newAutoOrderResult() interface{} {
	return &AutoOrderResult{}
}

type AutoOrderArgs struct {
	Req *ai.AutoOrderReq
}

func (p *AutoOrderArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(ai.AutoOrderReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *AutoOrderArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *AutoOrderArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *AutoOrderArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *AutoOrderArgs) Unmarshal(in []byte) error {
	msg := new(ai.AutoOrderReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var AutoOrderArgs_Req_DEFAULT *ai.AutoOrderReq

func (p *AutoOrderArgs) GetReq() *ai.AutoOrderReq {
	if !p.IsSetReq() {
		return AutoOrderArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *AutoOrderArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AutoOrderArgs) GetFirstArgument() interface{} {
	return p.Req
}

type AutoOrderResult struct {
	Success *ai.AutoOrderResp
}

var AutoOrderResult_Success_DEFAULT *ai.AutoOrderResp

func (p *AutoOrderResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(ai.AutoOrderResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *AutoOrderResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *AutoOrderResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *AutoOrderResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *AutoOrderResult) Unmarshal(in []byte) error {
	msg := new(ai.AutoOrderResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *AutoOrderResult) GetSuccess() *ai.AutoOrderResp {
	if !p.IsSetSuccess() {
		return AutoOrderResult_Success_DEFAULT
	}
	return p.Success
}

func (p *AutoOrderResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.AutoOrderResp)
}

func (p *AutoOrderResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AutoOrderResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) QueryOrder(ctx context.Context, Req *ai.OrderQueryReq) (r *ai.OrderQueryResp, err error) {
	var _args QueryOrderArgs
	_args.Req = Req
	var _result QueryOrderResult
	if err = p.c.Call(ctx, "QueryOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AutoOrder(ctx context.Context, Req *ai.AutoOrderReq) (r *ai.AutoOrderResp, err error) {
	var _args AutoOrderArgs
	_args.Req = Req
	var _result AutoOrderResult
	if err = p.c.Call(ctx, "AutoOrder", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
