apiVersion: v1
kind: Service
metadata:
  name: meilisearch-service
spec:
  selector:
    app: meilisearch
  ports:
    - name: http
      port: 7700
      targetPort: 7700
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.12.5
          ports:
            - containerPort: 7700
              name: http
          env:
            - name: MEILI_MASTER_KEY
              value: "abc123"  # 设置主密钥
          volumeMounts:
            - mountPath: /meili_data
              name: meili-data
          command: ["meilisearch", "--master-key", "abc123", "--db-path", "/meili_data"]
      volumes:
        - name: meili-data
          persistentVolumeClaim:
            claimName: meili-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meili-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi