apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      prometheusremotewrite:
        endpoint: "http://victoriametrics-service:8428/api/v1/write"

      debug:

      otlp/jaeger:
        endpoint: jaeger-service:4317
        tls:
          insecure: true

    processors:
      batch:

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [ pprof, zpages, health_check ]
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ debug, otlp/jaeger ]
        metrics:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ debug, prometheusremotewrite ]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
spec:
  selector:
    app: otel-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib-dev:latest
        args:
        - "--config=/etc/otel-collector-config.yaml"
        ports:
        - containerPort: 1888  # pprof extension
        - containerPort: 8888  # Prometheus metrics
        - containerPort: 8889  # Prometheus exporter
        - containerPort: 13133 # health check
        - containerPort: 4317  # OTLP gRPC
        - containerPort: 55679 # zpages
        volumeMounts:
        - name: otel-config
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-collector-config.yaml
      volumes:
      - name: otel-config
        configMap:
          name: otel-collector-config
