apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: default
data:
  GO_ENV: "online"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
    - name: grpc
      port: 8082
      targetPort: 8082
    - name: opentelemetry
      port: 4317
      targetPort: 4317
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: default
  labels:
    app: user
spec:
  # Pod 数量
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          # 镜像地址, Dockefile构建的镜像
          image: user-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: grpc
            - containerPort: 4317
              name: opentelemetry
            - containerPort: 8092
              name: health
          env:
            - name: GO_ENV
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: GO_ENV
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8092
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8092
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-deployment-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-deployment
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
