// Code generated by hertz generator.

package ai

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _autoorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryorderMw() []app.HandlerFunc {
	// your code...
	return nil
}
