// Code generated by hertz generator.

package main

import (
	"context"
	"log"
	"time"

	"2501YTC/app/gateway/biz/dal"
	"2501YTC/app/gateway/biz/dal/mysql"
	"2501YTC/app/gateway/biz/middleware"

	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"

	"2501YTC/app/gateway/biz/router"
	"2501YTC/app/gateway/conf"
	"2501YTC/app/gateway/infra/rpc"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/logger/accesslog"
	hertzlogrus "github.com/hertz-contrib/logger/logrus"
	"github.com/hertz-contrib/obs-opentelemetry/tracing"
	"github.com/hertz-contrib/pprof"
	"github.com/kitex-contrib/obs-opentelemetry/provider"
	"go.uber.org/zap/zapcore"
	"gopkg.in/natefinch/lumberjack.v2"
)

func main() {
	// init dal
	dal.Init()

	rpc.InitClient()

	casbinMiddleware, err := middleware.NewCasbinEnforcer(mysql.DB)
	if err != nil {
		log.Fatalf("初始化Casbin失败: %v", err)
	}
	casbinHandler := casbinMiddleware.Middleware()

	// 链路追踪
	p := provider.NewOpenTelemetryProvider(
		provider.WithServiceName(conf.GetConf().Hertz.Service),
		// Support setting ExportEndpoint via environment variables: OTEL_EXPORTER_OTLP_ENDPOINT
		provider.WithExportEndpoint(conf.GetConf().OpenTelemetry.Endpoint),
		provider.WithInsecure(),
	)
	defer func(p provider.OtelProvider, ctx context.Context) {
		err := p.Shutdown(ctx)
		if err != nil {
			hlog.Error(err)
		}
	}(p, context.Background())

	tracer, cfg := tracing.NewServerTracer()

	address := conf.GetConf().Hertz.Address
	h := server.New(tracer, server.WithHostPorts(address))
	h.Use(tracing.ServerMiddleware(cfg))
	registerMiddleware(h, casbinHandler)
	// registerMiddleware(h)
	// add a ping route to test
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})

	router.GeneratedRegister(h)

	h.Spin()
}

// casbinHandler app.HandlerFunc
func registerMiddleware(h *server.Hertz, casbinHandler app.HandlerFunc) {
	// log
	logger := hertzlogrus.NewLogger()
	hlog.SetLogger(logger)
	hlog.SetLevel(conf.LogLevel())
	asyncWriter := &zapcore.BufferedWriteSyncer{
		WS: zapcore.AddSync(&lumberjack.Logger{
			Filename:   conf.GetConf().Hertz.LogFileName,
			MaxSize:    conf.GetConf().Hertz.LogMaxSize,
			MaxBackups: conf.GetConf().Hertz.LogMaxBackups,
			MaxAge:     conf.GetConf().Hertz.LogMaxAge,
		}),
		FlushInterval: time.Minute,
	}
	hlog.SetOutput(asyncWriter)
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		_ = asyncWriter.Sync()
	})

	// pprof
	if conf.GetConf().Hertz.EnablePprof {
		pprof.Register(h)
	}

	// gzip
	if conf.GetConf().Hertz.EnableGzip {
		h.Use(gzip.Gzip(gzip.DefaultCompression))
	}

	// access log
	if conf.GetConf().Hertz.EnableAccessLog {
		h.Use(accesslog.New())
	}

	// recovery
	h.Use(recovery.Recovery())

	// cores
	h.Use(cors.Default())

	h.Use(middleware.JwtAuthMiddleware("(7oV#G2)mc%%dRrVh"))
	h.Use(casbinHandler)
}
