version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=order
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - /etc/localtime:/etc/localtime
      - ../../../config/mysql:/var/lib/mysql
      - ../../../logs/mysql/log:/var/log/mysql
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP 端口
      - "15672:15672"  # 管理界面端口
    environment:
      - RABBITMQ_DEFAULT_USER=guest  # 设置 RabbitMQ 默认用户名
      - RABBITMQ_DEFAULT_PASS=guest  # 设置 RabbitMQ 默认密码
